stages:
  - build
  - deploy
  - run

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

cache:
  paths:
    - .m2/repository

# 當 tag 被推送時執行組建
build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  only:
    - tags
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

# 當 tag 被推送時執行 Docker 建置和推送
docker-build-push:
  stage: deploy
  image: docker:24
  services:
    - docker:24-dind
  only:
    - tags
  dependencies:
    - build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

# 排程任務:每日 00:00 UTC 執行
scheduled-run:
  stage: run
  image: docker:24
  services:
    - docker:24-dind
  only:
    - schedules
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE_NAME
    - docker run --rm $IMAGE_NAME
